In [1]:
import numpy as np


In [2]:
vec = np.array([124,23,1,23,1,31,23,1,2])


it works right?

In [3]:
vec

array([124,  23,   1,  23,   1,  31,  23,   1,   2])

In [4]:
from sklearn.datasets import make_regression

data = make_regression()
data

(array([[-0.94222808,  0.28258373,  1.1881894 , ..., -1.4989834 ,
         -0.85853896,  1.36657271],
        [ 0.55191651,  0.74316611,  1.96425813, ..., -0.52495201,
         -0.43385545,  0.71588492],
        [-0.43773284, -0.00571932,  0.20258309, ...,  0.7890969 ,
         -0.46858443, -0.94648646],
        ...,
        [-0.28200631,  0.45373372, -0.35836378, ..., -0.94912751,
         -0.65250401,  1.48445109],
        [-0.59875477, -0.32703829, -1.74516894, ..., -1.40594738,
          1.39558013,  1.35967638],
        [-1.33429942, -1.08162014, -0.26258949, ..., -0.0386857 ,
         -0.31966423, -0.38466729]]),
 array([ 122.86979457,  145.4630701 ,  394.69442097,  100.96021362,
         363.4839403 ,  165.69163031, -319.41003271,  148.7067299 ,
         123.05286328, -318.51355325, -286.89479979,   -5.78031848,
        -237.50569997,  -90.81440937,   -2.7686294 ,  -49.67089898,
        -353.84868269, -231.93022534,   43.70681547,    8.50862486,
         -54.55365339,  172.88691

as you see here $g_{\mu\nu} = \frac{1}{2 \cdot \phi}$